### ISSUE TITLE
第六册上的目录是什么样？

### ISSUE THREAD

**Issue by A6669** [jamesfang8499/math6#3]
中学数学实验教材的第六册上，在各大网站都找不到，以至于有人怀疑他的存在，但是实际上是真实存在的，在孔夫子网的已售记录中可以找到这本书。[孔夫子](https://book.kongfz.com/0/6830449345/?encryptId=1uam)
希望买到这本书的人，能把电子版传给@jamesfang8499 让@jamesfang8499 能够完成第六册上的电子版的制作。

![1](https://github.com/jamesfang8499/math6/assets/3398776/a5145a6d-93f6-491e-a236-0b972bba1986)
![2](https://github.com/jamesfang8499/math6/assets/3398776/2bac3198-263c-4cad-87d4-c4b6e71a3d00)
![3](https://github.com/jamesfang8499/math6/assets/3398776/8b1e7b27-db89-4e84-8fcb-95816392c531)

**Comment by jamesfang8499** [comment]
感谢！在十一本教材的整理过程中，就发现缺少了复数以及排列组合的内容。想不到这块的知识是在第六册上册中。

**Comment by jamesfang8499** [comment]
感谢！在十一本教材的整理过程中，就发现缺少了复数以及排列组合的内容。想不到这块的知识是在第六册上册中。
