### ISSUE TITLE
关于中学数学实验教材的第六册上

### ISSUE THREAD

**Issue by a100xiaoxue** [jamesfang8499/math6#4]
中学数学实验教材在之后修订为初中数学实验教材与高中数学实验教材出版，而且根据目录来看，第六册上的内容分散到了高中数学实验教材代数下与几何下中；我已购买这两本书，并且由于其他几册的内容和高中数学实验教材中的内容（包括正文和题目）都高度相似，所以不知作者有没有意愿先以高中数学实验教材的这几章内容代替中学数学实验教材第六册上进行重排版，有人可以联系上作者吗

**Comment by a100xiaoxue** [comment]
https://www0.kfzimg.com/sw/kfz-cos/kfzimg/deccbfad/07a619ab2e35bc24_b.jpg
不过确实有删减，复数这里删了好多内容

**Comment by a100xiaoxue** [comment]
不知大佬觉得可以吗，如果可以的话我想要一个上传文件的权限，我拍照上传到仓库里

**Comment by syhily** [comment]
@a100xiaoxue 

第六册上册目录已经有人放出。

![image](https://github.com/jamesfang8499/math6/assets/1761698/c677be74-1357-4c21-9ee8-8fe84c24c47f)
![image](https://github.com/jamesfang8499/math6/assets/1761698/607ca946-2653-4479-9d2d-382af24ff79c)

**Comment by jamesfang8499** [comment]
感谢各位提供的信息，第六册（上）的电子文档已经获得，数位化即将进行
