### ISSUE TITLE
中学实验教材第六册上 pdf 下载

### ISSUE THREAD

**Issue by A6669** [jamesfang8499/math6#5]
神隐多年的第六册上，终于现出了他的真面目，希望阁下可以把这本也LaTeX化，将整套中学实验教材补完。
https://zhuanlan.zhihu.com/p/698083965?utm_psn=1774738209026793472

https://z-library.se/book/28596044/fae3ae/%E4%B8%AD%E5%AD%A6%E6%95%B0%E5%AD%A6%E5%AE%9E%E9%AA%8C%E6%95%99%E6%9D%90-%E7%AC%AC%E5%85%AD%E5%86%8C%E4%B8%8A.html

**Comment by jamesfang8499** [comment]
感谢！
