### ISSUE TITLE
中学数学实验教材（第六册上）

### ISSUE THREAD

**Issue by WisdomLove** [jamesfang8499/math6#6]
中学数学实验教材（第六册上）  X.com上有了，求速度更新

https://pan.baidu.com/s/1S3wCrNrn-EIokMAbbyxqVQ

a2iv

**Comment by syhily** [comment]
FYI: https://github.com/jamesfang8499/math6/issues/5

**Comment by WisdomLove** [comment]
非常感恩

**Comment by WisdomLove** [comment]
Done
